### ISSUE TITLE
Error using the package

### ISSUE THREAD

**Issue by flockonus** [MortenHoustonLudvigsen/process-promises#1]
`split` need to be moved into dependency instead of devDependency

```
module.js:338
    throw err;
          ^
Error: Cannot find module 'split'
    at Function.Module._resolveFilename (module.js:336:15)
    at Function.Module._load (module.js:278:25)
    at Module.require (module.js:365:17)
    at require (module.js:384:17)
    at Object.<anonymous> (/Users/flockonus/workspace/aaa/bbb/node_modules/process-promises/lib/process-promises.js:3:13)
```

**Comment by radarsu** [comment]
I fixed it in pull https://github.com/MortenHoustonLudvigsen/process-promises/pull/2.

Also, if you'd like to use my module fork you can use `npm i radarsu/process-promises` or `yarn add radarsu/process-promises`

**Comment by flockonus** [comment]
Very cool, and thanks for the heads up!
